name: windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        version: [1.16.x, 1.17.x, 1.18.x]
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -failfast -race  ./... -timeout=5m

